### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by cmkohnen** [Sjoerd1993/Graphs#209]
Just opening this as an issue to track tasks for the next release. I haven't found any more bugs or oddities whilst testing on my end.

## TODO-List
- [x] Write general changelist (done in https://github.com/Sjoerd1993/Graphs/issues/201#issuecomment-1504821312)
- [x] Use changelist in appstream data and whats_new
- [x] Create new screenshots
         Sorry for not replying to https://github.com/Sjoerd1993/Graphs/pull/192#issuecomment-1502851524 sooner, 
         in general I would prefer having them on GitHub, as this makes it easier to update them, as you already pointed out. Regarding
         text in the screenshots I'm not quite sure. I do believe these features are the ones we probably want to showcase, but I haven't seen
         any other project put descriptive text in their screenshots. If we were to arrange the main feature highlights in the same order as
         the screenshots, that might work in my opinion.
- [x] Update Project description(?)
         We might want to update the project description to highlight all current functionality (readme, doap and appstream)
- [x] Update readme 
         We might want to add a bit of information to the readme, namely how to build manually and how to contribute and make it
         a bit more appealing in general
- [x] Fix any bugs we might find in the process
- [ ] Bump version number and tag on github
- [ ] Update flathub build

For any additions or changes feel free to edit

**Comment by Sjoerd1993** [comment]
Regarding having a text-based description in the screenshot itself, I saw one project doing it and it seemed helpful to highlight stuff. But on the other hand it does shrink the available screen estate, which already is limited on e.g. GNOME Software. Either way, I looked at the actual guidelines that exist on this (which Flathub refers to), and it's best to avoid anything other than the software itself in the screenshot so I'd guess we should just go with "regular" screenshots: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html. I think we'll just put the Screenshots on Github then, to have them nicely centralized with the rest of the project and be able to update them easily as well with a simple PR.

I think both the project description and the readme indeed need updating before releasing as well.

I've updated the Flathub beta build yesteday to the latest build, and just put a PR to update it again (it has to build succesfully before I can merge that): https://github.com/flathub/se.sjoerd.Graphs/pull/10  
In principle for the final build there's not a lot to do apart from updating the commit in the beta branch to the then stable version, and then merging beta with main.

**Comment by Sjoerd1993** [comment]
I've updated the beta branch on Flathub to the latest build by the way. I did have to change the appdata date, as the Flatpak buildbot doesn't accept release dates that are invalid or lie in the future hence the separate branch.

Also bumped the version number there, but didn't add 'buildtype=release' to the meson.build options there yet, as it's still a development version after all.

https://github.com/flathub/se.sjoerd.Graphs/pull/12

**Comment by cmkohnen** [comment]
With the current progress towards the release, I'm kind of inclined to publish today, if no complications occur. 
Regarding setting the buildtype, I think it's best to set it in the flatpak manifest as a meson option, so any other build that is not the "official" flatpak release still retains the development status.

**Comment by Sjoerd1993** [comment]
Everything works fine on the Flathub beta branch, so I'm happy releasing today. If you put up a PR with the updated tag and buildtype (in the flatpak manifest is OK), I'll push the update to Flathub. Also the appdata release data should be updated to today then for the Flathub build to actually build.
