### ISSUE TITLE
GNOME Circle feedback tracker

### ISSUE THREAD

**Issue by Sjoerd1993** [Sjoerd1993/Graphs#385]
We've received initial feedback on our [GNOME Circle application](https://gitlab.gnome.org/Teams/Circle/-/issues/185), resulting in a list of suggestions that we will adress. This issue is mean to track the progress on the given feedback so far:

Feedback round 1
---------------------
- [x]  Canvas navigation feels a bit clunky, is scroll/pinch-to-zoom out of the question with the widgetry you're using for the graph?

- [x] I wonder if the expanders in the tools section are needed, since most of the sections aren't that long. Perhaps it could be just three sections with a standard header?

- [x]  I'd move "Translate and Multiply" down to be the last section, since the other two are more similar

- [x]  These entry rows look a bit odd. I'd try regular entries, and using the same width for the buttons to make them all align horizontally.

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/278d5422-e3f2-4760-ad01-8d2c9a2d20ec)

- [x]  The app has lots of settings, it'd be good to review if all of them are necessary/being used. If you're not sure something's being used it's often better to just choose a reasonable default, because it makes it easier to find the important settings. For example, is it really necessary to have a setting for clipboard length? Could it just be unlimited? If not, are you aware of cases where someone would explicitly seek out the option?

- [x]  Many listboxes (especially in Preferences) have both a title and a subtitle, but the subtitle is just restating the title. In these cases it's better to omit the subtitile.

- [x]  Similarly, many listbox rows have both title and subtitle, with the subtitle being very similar to the title. I'd do the same thing here and drop the subtitle if it doesn't add much.

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/dad513d4-472e-420e-9cba-52385b15a879)

- [x]  If we keep these options (which I'm not totally sure are necessary) I'd use the same 3 column layout from the "Add Equation" dialog - removed

![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/6e64001d-67d6-4377-9cf4-3e6b319ce288)

Feedback round 2
-----------------------

- [x] This menu is a bit wide, which looks awkward. Perhaps the equation string could be shortened to "Add Equation..."? I'd also drop the divider between the two options, it seems unnecessary with just 2 items.
![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/2441f77b-010f-4312-ab54-db5f8050329a)

- [x]  The prev/next view arrows are a bit small, maybe they should use the normal go-forward and go-back icons? It's also a bit odd to have this and the undo/redo icons in the same toolbar, but I don't have a better idea.
![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/72ffe742-5ce3-4cea-8570-17cb2926156e)

- [x] The style dialog is not great, it's just a list of strings with no previews of what the styles look like
- [x]  The style editor views don't seem to be using ToolbarView
![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/84a22896-7a87-4576-94ed-d20e995a7bf6)

- [x]  I'd make this a pill button, and drop .suggested-action
![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/96847d85-0d01-4822-af1e-67e10de1c194)

- [x]  Preferences dialogs with just a handful of options should disable search
![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/a974cf3a-07e7-431f-845e-389f8a85f19b)

- [x] The graph grid styling feels a bit heavy. I'd try using lighter grays for all the grid lines, particularly the very dark outlines.
![image](https://github.com/Sjoerd1993/Graphs/assets/68477016/57ad2c94-fdde-48e8-ac22-2041ad799a03)

**Comment by Sjoerd1993** [comment]
I tried to implement a scroll to zoom functionality. The basic feature is very easy to implement with a scroll event, but for some reason the scroll event does not accurately capture the correct data points for xdata and ydata. Meaning I can't get it to work to actually zoom into the position wherever the pointer is located. 

I tried to see if I can couple it to the built-in for right-click+panning (currently disabled in Graphs), as that does exactly what I want here. But got stuck there as well.
